name: 'customer_reporting_consolidation'
version: '1.0.0'
config-version: 2

profile: 'dbt_bigquery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: "chris_rudolph_gcs_mdls"
  tenant_schema_seed_name: "tenant_schemas"

models:
  customer_reporting_consolidation:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  customer_reporting_consolidation:
    +quote_columns: false
